# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Windows Build And Deploy

on:
  push:
    branches: [ "main", "dev" ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.3

    - name: Build
      run: |
        go build main.go
  
    - name: Scp
      uses: garygrossgarten/github-action-scp@release
      with:
        local: main.exe
        remote: main.exe
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        privateKey: ${{ secrets.KEY }}

    - name: Deploy
      uses: appleboy/ssh-action@master
      env:
        BUILDPATH: ${{ screts.PATH }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        envs: BUILDPATH
        script: |
          set CUR_YYYY=%date:~10,4%
          set CUR_MM=%date:~4,2%
          set CUR_DD=%date:~7,2%
          set CUR_HH=%time:~0,2%
          if %CUR_HH% lss 10 (set CUR_HH=0%time:~1,1%)
          set CUR_NN=%time:~3,2%
          set CUR_SS=%time:~6,2%
          set CUR_MS=%time:~9,2%
          set SUBFILENAME=%CUR_YYYY%%CUR_MM%%CUR_DD%%CUR_HH%%CUR_NN%
          mkdir %BUILDPATH%\backup\%SUBFILENAME%
          copy %BUILDPATH%\main.exe %BUILDPATH%\backup\%SUBFILENAME%
          taskkill /f /im main.exe
          del %BUILDPATH%\main.exe
