name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: test
      run: |
        go version
        export GOOS=windows
        export GOARCH=amd64
        go build main.go
        ls -al
        

    - name: Copy single file to remote
      uses: garygrossgarten/github-action-scp@release
      with:
        local: main.exe
        remote: soominTest/main.exe
        host: ${{ secrets.DEVELOPERS }}
        username: ${{ secrets.USERNAME }}
        privateKey: ${{ secrets.DEVELOPERS_KEY }}

        
    - name: executing remote ssh commands using key
#       id: script
      uses: appleboy/ssh-action@master
      env:
        BUILDPATH: ${{ secrets.PATH }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        envs: BUILDPATH
        script: |
          set CUR_YYYY=%date:~10,4%
          set CUR_MM=%date:~4,2%
          set CUR_DD=%date:~7,2%
          set CUR_HH=%time:~0,2%
          if %CUR_HH% lss 10 (set CUR_HH=0%time:~1,1%)
          set CUR_NN=%time:~3,2%
          set CUR_SS=%time:~6,2%
          set CUR_MS=%time:~9,2%
          set SUBFILENAME=%CUR_YYYY%%CUR_MM%%CUR_DD%%CUR_HH%%CUR_NN%
          mkdir %BUILDPATH%\backup\%SUBFILENAME%
          copy %BUILDPATH%\main.exe %BUILDPATH%\backup\%SUBFILENAME%
          taskkill /f /im main.exe
          del %BUILDPATH%\main.exe
