name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: test
      run: |
        go version
        export GOOS=windows
        export GOARCH=amd64
        go build main.go
        ls
        
    - name: ls test
      run: |
        ls
        
    - name: executing remote scp commands using key
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEVELOPERS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.DEVELOPERS_KEY }}
        port: 22
        source: "main.exe"
        
    - name: executing remote ssh commands using key
      id: script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEVELOPERS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.DEVELOPERS_KEY }}
        port: 22
        script: |
          dir
        
