name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: test
      run: |
        go version
        
    - name: executing remote ssh commands using key
      id: script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEVELOPERS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.DEVELOPERS_KEY }}
        port: 22
        script_stop: true
        continue-on-error: true
        script: |
          dir
          cd ..
          dir
          start /b hi.cmd
          ping 127.0.0.1 -n 60 > nul
          netstat -ano|findstr 8436
    - run: echo '${{ steps.script.outputs.result }}'
