# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: |
        go build -v ./main.go
        ls -al
        
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        mkdir ../build
        cp -TR . ../build
        tar -cvf deploy.tar ../build/
    
    - name: Send file to FileDown
      uses: appleboy/scp-action@v0.1.3
      with: 
        host: ${{ secrets.EXTENSION_HOST }}
        username: ${{ secrets.EXTENSION_USERNAME }}
        key: ${{ secrets.EXTENSION_KEY }}
        port: 22
        source: "deploy.tar"
        target: "destination/folder"
        debug: true
      
    - name: executing remote ssh commands using key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EXTENSION_HOST }}
        username: ${{ secrets.EXTENSION_USERNAME }}
        key: ${{ secrets.EXTENSION_KEY }}
        port: 22
        script: |
          cd /home/ubuntu/destination/folder
          tar -xvf deploy.tar
          cd /home/ubuntu/destination/folder/build
          cp main /home/ubuntu/github_action
          rm -rf /home/ubuntu/destination
          PID=$(pgrep main)
          sudo kill -9 $PID
          cd /home/ubuntu
          mkdir /home/ubuntu/backup/$(date +"%Y%m%d%H")
          mv main /home/ubuntu/backup/$(date +"%Y%m%d%H")
          cd /home/ubuntu/github_action
          cp main /home/ubuntu
          sudo nohup /home/ubuntu/main </dev/null >/dev/null 2>&1 &
