# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
      
    - name: executing remote ssh commands using key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEVELOPERS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.DEVELOPERS_KEY }}
        port: 22
        script: |
          type nul > C:/deploy/developers/filename2.txt
          pwd
          C:/deploy/developers/soomin.ps1
          sleep 10 &&
          type nul > C:/deploy/developers/filename.txt
          

    
